package ledger

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type FullExport struct {
	GeneratedAt string         `json:"generatedAt"`
	Events      []InstallEvent `json:"events"`
	Inventory   *Inventory     `json:"inventory,omitempty"`
}

func exportsDir() string {
	return filepath.Join(ledgerDir(), "exports")
}

func Export(format string, outPath string) error {
	format = strings.ToLower(strings.TrimSpace(format))

	switch format {
	case "markdown", "md":
		return ExportMarkdown(outPath)
	case "json":
		return ExportJSON(outPath)
	case "brewfile":
		return ExportBrewfile(outPath)
	default:
		return fmt.Errorf("unknown export format: %s\nUse: markdown, json, or brewfile", format)
	}
}

func ExportMarkdown(outPath string) error {
	events, err := ReadEvents()
	if err != nil {
		return err
	}

	inventory, _ := readInventory()

	if outPath == "" {
		outPath = defaultExportPath("install-ledger", "md")
	}

	var b strings.Builder

	b.WriteString("# Install Ledger Export\n\n")
	b.WriteString(fmt.Sprintf("Generated at: `%s`\n\n", time.Now().Format(time.RFC3339)))

	if inventory != nil {
		b.WriteString("## System\n\n")
		writeMarkdownKV(&b, "Scanned at", inventory.ScannedAt)
		writeMarkdownKV(&b, "OS", inventory.System["os"])
		writeMarkdownKV(&b, "Kernel", inventory.System["kernel"])
		writeMarkdownKV(&b, "Machine", inventory.System["machine"])
		writeMarkdownKV(&b, "Host", inventory.System["hostname"])

		b.WriteString("\n")
		b.WriteString("## Inventory Summary\n\n")
		writeMarkdownCount(&b, "Homebrew manual packages", inventory.Tools["brew_leaves"], countCleanLines)
		writeMarkdownCount(&b, "npm global packages", inventory.Tools["npm_global"], countNPMGlobals)
		writeMarkdownCount(&b, "pipx tools", inventory.Tools["pipx"], countCleanLines)
		writeMarkdownCount(&b, "uv tools", inventory.Tools["uv_tools"], countUVTools)
		writeMarkdownCount(&b, "conda environments", inventory.Tools["conda_envs"], countCondaEnvs)
		writeMarkdownCount(&b, "VS Code extensions", inventory.Tools["vscode_extensions"], countCleanLines)
		b.WriteString("\n")
	}

	b.WriteString("## Install Events\n\n")

	if len(events) == 0 {
		b.WriteString("_No structured install events found._\n")
	} else {
		currentDate := ""

		for i := len(events) - 1; i >= 0; i-- {
			event := events[i]
			eventTime, ok := parseEventTime(event)
			if !ok {
				continue
			}

			dateLabel := eventTime.Format("2006-01-02")
			if dateLabel != currentDate {
				b.WriteString(fmt.Sprintf("\n### %s\n\n", dateLabel))
				currentDate = dateLabel
			}

			b.WriteString(fmt.Sprintf("- `%s` **%s** `%s`",
				eventTime.Format("15:04"),
				event.Manager,
				humanEvent(event),
			))

			if event.CWD != "" {
				b.WriteString(fmt.Sprintf("  \n  Path: `%s`", event.CWD))
			}

			if event.RawCommand != "" {
				b.WriteString(fmt.Sprintf("  \n  Command: `%s`", event.RawCommand))
			}

			b.WriteString("\n")
		}
	}

	if err := writeExportFile(outPath, []byte(b.String())); err != nil {
		return err
	}

	fmt.Println("Markdown export saved:", expandHomePath(outPath))
	return nil
}

func ExportJSON(outPath string) error {
	events, err := ReadEvents()
	if err != nil {
		return err
	}

	inventory, _ := readInventory()

	if outPath == "" {
		outPath = defaultExportPath("install-ledger", "json")
	}

	payload := FullExport{
		GeneratedAt: time.Now().Format(time.RFC3339),
		Events:      events,
		Inventory:   inventory,
	}

	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return err
	}

	if err := writeExportFile(outPath, data); err != nil {
		return err
	}

	fmt.Println("JSON export saved:", expandHomePath(outPath))
	return nil
}

func ExportBrewfile(outPath string) error {
	inventory, err := readInventory()
	if err != nil || inventory == nil {
		fmt.Println("No inventory found yet.")
		fmt.Println("Run: il scan")
		return nil
	}

	if outPath == "" {
		outPath = filepath.Join(exportsDir(), "Brewfile")
	}

	packages := cleanLines(inventory.Tools["brew_leaves"])
	if len(packages) == 0 {
		fmt.Println("No Homebrew manual packages found in inventory.")
		fmt.Println("Run: il scan")
		return nil
	}

	var b strings.Builder

	b.WriteString("# Generated by Install Ledger\n")
	b.WriteString(fmt.Sprintf("# Generated at: %s\n\n", time.Now().Format(time.RFC3339)))

	for _, pkg := range packages {
		pkg = strings.TrimSpace(pkg)
		if pkg == "" {
			continue
		}

		b.WriteString(fmt.Sprintf("brew \"%s\"\n", pkg))
	}

	if err := writeExportFile(outPath, []byte(b.String())); err != nil {
		return err
	}

	fmt.Println("Brewfile export saved:", expandHomePath(outPath))
	return nil
}

func readInventory() (*Inventory, error) {
	data, err := os.ReadFile(inventoryFile())
	if err != nil {
		return nil, err
	}

	var inventory Inventory
	if err := json.Unmarshal(data, &inventory); err != nil {
		return nil, err
	}

	return &inventory, nil
}

func defaultExportPath(prefix string, ext string) string {
	filename := fmt.Sprintf("%s-%s.%s",
		prefix,
		time.Now().Format("20060102-150405"),
		ext,
	)

	return filepath.Join(exportsDir(), filename)
}

func writeExportFile(path string, data []byte) error {
	if path == "" {
		return fmt.Errorf("export path is empty")
	}

	path = expandHomePath(path)
	dir := filepath.Dir(path)

	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(path, data, 0644)
}

func expandHomePath(path string) string {
	if path == "~" {
		home, _ := os.UserHomeDir()
		return home
	}

	if strings.HasPrefix(path, "~/") {
		home, _ := os.UserHomeDir()
		return filepath.Join(home, strings.TrimPrefix(path, "~/"))
	}

	return path
}

func writeMarkdownKV(b *strings.Builder, key string, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}

	b.WriteString(fmt.Sprintf("- **%s:** `%s`\n", key, value))
}

func writeMarkdownCount(b *strings.Builder, label string, raw string, count func(string) int) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		b.WriteString(fmt.Sprintf("- **%s:** not found / empty\n", label))
		return
	}

	total := count(raw)
	if total == 0 {
		b.WriteString(fmt.Sprintf("- **%s:** not found / empty\n", label))
		return
	}

	b.WriteString(fmt.Sprintf("- **%s:** %d\n", label, total))
}
